### ISSUE TITLE
No Parse Path Usage Example

### ISSUE THREAD

**Issue by bionicles** [ln613/ipath#1]
How do you use this module to get objects?

What if we need to look at the data to make the update?

Do immutable objects impede pass-by-reference / index-free adjacency?

**Comment by ln613** [comment]
Thanks for your input!

For your first question, what exactly are you trying to achieve? Could you provide code samples?

2nd question, just added a feature, the 3rd param (value) can now be a function that takes the current value, e.g.,

`update({ a: { b: 1 } }, 'a.b', x => x + 1)`

already published as v0.2.0. Readme also updated.

3rd question, when you pass an object into a function, it's always pass-by-reference, but the content of the object can be modified by the function. Immutable objects can help you avoid changing input objects, so I would say it actually helps with pass-by-reference. As for index-free adjacency, I don't see a relation here, we are not talking about graph data here.
